package nl.praegus.fitnesse.slim.fixtures.totp;

import com.warrenstrange.googleauth.GoogleAuthenticator;
import com.warrenstrange.googleauth.GoogleAuthenticatorConfig;
import nl.hsac.fitnesse.fixture.slim.SlimFixture;
import nl.hsac.fitnesse.fixture.slim.SlimFixtureException;

/**
 * This fixture generates a Time-bases One Time Password (TOPT). That is the same code that is generated by e.g.
 * the Google Authenticator app. The fixture uses the library found on https://github.com/wstrange/GoogleAuth.
 * <p>
 * In order to get a correct TOTP you need:
 * - the secret. Generally this is encoded in the QR code. Many platforms, however, also have options to show the
 * unencoded secret in order to manually add an account to your authenticator app. This unencoded secret is needed by
 * this fixture in order to generate the TOTP
 * - The machine executing the fixture should have the time set correctly. Practically this means that its time should
 * be synced with a NTP server.
 */

public class TotpFixture extends SlimFixture {
    GoogleAuthenticatorConfig.GoogleAuthenticatorConfigBuilder configBuilder
            = new GoogleAuthenticatorConfig.GoogleAuthenticatorConfigBuilder();

    public void setNumberOfDigits(int numberOfDigits) {
        if (numberOfDigits < 6 || numberOfDigits > 8) {
            throw new SlimFixtureException("TOTP length needs to be > 6 and < 8");
        }
        configBuilder.setCodeDigits(numberOfDigits);
    }

    public String getTOTPForSecret(String secretKey) {
        GoogleAuthenticatorConfig gAuthConfig = configBuilder.build();
        GoogleAuthenticator gAuth = new GoogleAuthenticator(gAuthConfig);
        int totp = gAuth.getTotpPassword(secretKey);
        /**
         * GoogleAuthenticator returns code as an int and so can't have leading zeros. This means that the generated code
         * can have a length shorter than the configured length (defaults to 6). This is solved by adding leading zero's
         */
        return TotpUtils.padCodeWithZerosToNumberOfDigits(totp, gAuthConfig.getCodeDigits());
    }
}
